name: Update gist
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: janghana/productive-box@master
        with:
          node-version: '12.13.0'
          check-latest: true
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ 1c8feef106039dd27e5a545ea14f40be }}
          TIMEZONE: Asia/Seoul
